apiVersion: v1
kind: Service
metadata:
  labels:
    run: mlvx-pilbox
  name: mlvx-pilbox-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    run: mlvx-pilbox
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
