apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: mlvx-pilbox
  name: mlvx-pilbox
  namespace: default
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/mlvx-pilbox
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: mlvx-pilbox
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mlvx-pilbox
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: uber-pool
      containers:
      - image: gcr.io/shoebox-encoding/mlvx-pilbox:1.3.4-simd
        imagePullPolicy: Always
        name: mlvx-pilbox
        ports:
        - containerPort: 8888
          protocol: TCP
        resources:
          limits:
            memory: 20Gi
          requests:
            cpu: 1
            memory: 10Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
